// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJzBLB5qaens2TPm_NJYzFobzjfydaXLs',
    appId: '1:54879710224:web:81f2b98d6b8ca75cb1ae95',
    messagingSenderId: '54879710224',
    projectId: 'socialmediaapp-8d8c3',
    authDomain: 'socialmediaapp-8d8c3.firebaseapp.com',
    storageBucket: 'socialmediaapp-8d8c3.appspot.com',
    measurementId: 'G-0J5E2JQ1GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpT2xvghp2t0c60pvWy_zp0Tughi3ptFE',
    appId: '1:54879710224:android:64441824e13fc95ab1ae95',
    messagingSenderId: '54879710224',
    projectId: 'socialmediaapp-8d8c3',
    storageBucket: 'socialmediaapp-8d8c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjE-HkDIg95N2r0Y1e-pWRlqJJZq0ttWA',
    appId: '1:54879710224:ios:8c34f79b27ed1b56b1ae95',
    messagingSenderId: '54879710224',
    projectId: 'socialmediaapp-8d8c3',
    storageBucket: 'socialmediaapp-8d8c3.appspot.com',
    iosClientId:
        '54879710224-tv6ljitengap4dl7md1cs7peqf01gtk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialmediaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjE-HkDIg95N2r0Y1e-pWRlqJJZq0ttWA',
    appId: '1:54879710224:ios:8c34f79b27ed1b56b1ae95',
    messagingSenderId: '54879710224',
    projectId: 'socialmediaapp-8d8c3',
    storageBucket: 'socialmediaapp-8d8c3.appspot.com',
    iosClientId:
        '54879710224-tv6ljitengap4dl7md1cs7peqf01gtk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialmediaapp',
  );
}
